export const PORTFOLIO = [
  {
    image: '/assets/images/portfolio/design/cup.jpg',
    title: 'Merchandise Design',
    // subtitle: 'Design Work',
    category: 'DESIGN',
    link: '',
  },
  {
    image: '/assets/images/portfolio/design/note_pad.jpg',
    title: 'Notepad Design',
    // subtitle: 'Design Work',
    category: 'DESIGN',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/design/rate_card.jpg',
    title: 'Corporate Rate Card Design',

    category: 'DESIGN',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/design/standee.jpg',
    title: 'Standee Design',
    // subtitle: 'Design Work',
    category: 'DESIGN',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/design/tant_card.jpg',
    title: 'Table Tents Cards Design',
    // subtitle: 'Design Work',
    category: 'DESIGN',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/design/web_cam.jpg',
    title: 'Packaging & Label Design',
    // subtitle: 'Design',
    category: 'DESIGN',
    link: '#',
  },
  // design section end

  // social media part start
  // dermapuritys

  {
    image: '/assets/images/portfolio/Dermapuritys/01.png',
    title: 'Dermapuritys',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/Dermapuritys/02.png',
    title: 'Dermapuritys',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/Dermapuritys/03.png',
    title: 'Dermapuritys',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // cms sir
  {
    image: '/assets/images/portfolio/cm_sir/01.png',
    title: 'UPSC With CM Sir',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/cm_sir/02.jpg',
    title: 'UPSC With CM Sir',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/cm_sir/03.jpg',
    title: 'UPSC With CM Sir',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // influenzr
  {
    image: '/assets/images/portfolio/influenzr/01.jpg',
    title: 'Influenzr',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/influenzr/02.jpg',
    title: 'Influenzr',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/influenzr/03.jpg',
    title: 'Influenzr',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // kilkari care foundation
  {
    image: '/assets/images/portfolio/kilkari/01.jpg',
    title: 'Kilkari Care Foundation',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/kilkari/02.jpg',
    title: 'Kilkari Care Foundation',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/kilkari/03.jpg',
    title: 'Kilkari Care Foundation',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // masterstroke
  {
    image: '/assets/images/portfolio/masterstroke/01.jpg',
    title: 'Master Stroke Salon & Academy',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/masterstroke/02.jpg',
    title: 'Master Stroke Salon & Academy',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/masterstroke/03.jpg',
    title: 'Master Stroke Salon & Academy',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // nab
  {
    image: '/assets/images/portfolio/nab/01.jpg',
    title: 'National Association For The Blind, Delhi',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/nab/02.jpg',
    title: 'National Association For The Blind, Delhi',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/nab/03.jpg',
    title: 'National Association For The Blind, Delhi',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // nation ngo
  {
    image: '/assets/images/portfolio/national_ngo/01.jpg',
    title: 'National NGO',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/national_ngo/02.jpg',
    title: 'National NGO',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/national_ngo/03.jpg',
    title: 'National NGO',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // pooja walia studio
  {
    image: '/assets/images/portfolio/pooja-walia-studio/01.jpg',
    title: 'Pooja Walia Studio',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/pooja-walia-studio/02.jpg',
    title: 'Pooja Walia Studio',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/pooja-walia-studio/03.jpg',
    title: 'Pooja Walia Studio',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // save the quest
  {
    image: '/assets/images/portfolio/stq/01.jpg',
    title: 'Save The Quest',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/stq/02.jpg',
    title: 'Save The Quest',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/stq/03.jpg',
    title: 'Save The Quest',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // tms
  {
    image: '/assets/images/portfolio/tms/01.jpg',
    title: 'TMS Family Salon',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/tms/02.jpg',
    title: 'TMS Family Salon',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/tms/03.jpg',
    title: 'TMS Family Salon',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  // youngman
  {
    image: '/assets/images/portfolio/youngman/01.jpg',
    title: 'Youngman India',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/youngman/02.jpg',
    title: 'Youngman India',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/youngman/03.jpg',
    title: 'Youngman India',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },

  // Dermavilla

  {
    image: '/assets/images/portfolio/Dermavilla/01.png',
    title: 'Dermavilla',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/dermavilla/02.png',
    title: 'Dermavilla',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/dermavilla/03.png',
    title: 'Dermavilla',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },

  // RejuvaPlus

  {
    image: '/assets/images/portfolio/RejuvaPlus/01.png',
    title: 'Rejuva Plus',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/RejuvaPlus/02.png',
    title: 'Rejuva Plus',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/RejuvaPlus/03.png',
    title: 'Rejuva Plus',
    // subtitle: 'Social Media Work',
    category: 'SOCIALMEDIA',
    link: '#',
  },

  // video tab start

  {
    title: 'Youngman India, Corporate Film',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: '0KCJEyaJucI',
    video: true,
  },
  {
    title: 'Fortino Dental, Clinic Tour',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'sAX_doZEfn4',
    video: true,
  },
  {
    title: 'Khidmat Restaurant,Interior Showcase',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'Rc3VGYfxPZA',
    video: true,
  },
  {
    title: 'DermaPuritys, Client Testimonial',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'BMcFH_E-psc',
    video: true,
  },
  {
    title: 'National NGO, Fundraising Video',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'qyVNdBlireU',
    video: true,
  },
  {
    title: 'Fortino Dental, Launch Event',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'miSJ_Puvq34',
    video: true,
  },
  {
    title: 'DermaPuritys, Event Teaser',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'guiLSpI1Y8w',
    video: true,
  },
  {
    title: 'National Association For The Blind, Fundraising Video',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'O-rOculLXZE',
    video: true,
  },
  {
    title: 'Pooja Walia Studio, Client Testimonial',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'rcHvANXWQKM',
    video: true,
  },
  {
    title: 'Youngman India, Corporate Film',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'gBAXereey-A',
    video: true,
  },
  {
    title: 'National NGO, Fundraising Video',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'HOceBELo-vQ',
    video: true,
  },
  {
    title: 'DermaPuritys, Launch Event',
    // subtitle: 'Social Media Work',
    category: 'VIDEOS',
    id: 'dKNJN6ursAs',
    video: true,
  },

  // video section end
  // digital campaigns section start
  {
    image: '/assets/images/portfolio/digital_campaigns/01.png',
    title: 'Influenzr',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/02.png',
    title: 'Influenzr',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/03.png',
    title: 'Influenzr',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/04.png',
    title: 'National NGO, Fundraising Video',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/05.png',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/06.png',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/07.png',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/08.png',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/09.png',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/10.png',
    title: 'Aroma Ladies Beauty Parlour',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/11.png',
    title: 'Aroma Ladies Beauty Parlour',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/12.png',
    title: 'Secret Leaves',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/13.png',
    title: 'Secret Leaves',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/14.png',
    title: 'Save The Quest',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/digital_campaigns/15.png',
    title: 'Save The Quest',
    // subtitle: 'Social Media Work',
    category: 'DIGITALCAMPAIGNS',
    link: '#',
  },
  // digital campaigns section end
  // print work start

  {
    image: '/assets/images/portfolio/printwork/1.jpg',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'PRINTWORK',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/printwork/2.jpg',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'PRINTWORK',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/printwork/3.jpg',
    title: 'DermaPuritys',
    // subtitle: 'Social Media Work',
    category: 'PRINTWORK',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/printwork/4.jpg',
    title: 'Just Accounting',
    // subtitle: 'Social Media Work',
    category: 'PRINTWORK',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/printwork/5.jpg',
    title: 'Rejuva Plus',
    // subtitle: 'Social Media Work',
    category: 'PRINTWORK',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/printwork/6.jpg',
    title: 'Rejuva Plus',
    // subtitle: 'Social Media Work',
    category: 'PRINTWORK',
    link: '#',
  },

  // print work end
  // websit design & development
  {
    image: '/assets/images/portfolio/app-img4.jpg',
    title: 'DermaPuritys',
    subtitle: 'Cosmetic Dermatology',
    category: 'WEBSITE',
    link: 'https://dermapuritys.com/',
  },
  {
    image: '/assets/images/portfolio/app-img7.jpg',
    title: 'NGO ,National CRS',
    subtitle: 'National CRS',
    category: 'WEBSITE',
    link: 'https://ncrsngo.org/',
  },
  {
    image: '/assets/images/portfolio/save-the-quest.jpg',
    title: 'NGO ,Save The Quest',
    subtitle: 'National NGO, STQ',
    category: 'WEBSITE',
    link: 'https://savethequest.org/',
  },
  {
    image: '/assets/images/portfolio/app-img8.jpg',
    title: 'NOFSE',
    subtitle: 'NOFSE, National NGO',
    category: 'WEBSITE',
    link: 'https://nationalngo.net/',
  },
  {
    image: '/assets/images/portfolio/app-img9.jpg',
    title: 'S koley',
    subtitle: 'Construction Company',
    category: 'WEBSITE',
    link: 'https://www.skoley.com/',
  },
  {
    image: '/assets/images/portfolio/app-img10.jpg',
    title: 'PGX Motors',
    subtitle: 'Vehicle Parts Shop',
    category: 'WEBSITE',
    link: 'https://pgxmotoshoppe.com/',
  },
  {
    image: '/assets/images/portfolio/app-img11.jpg',
    title: 'Luhaif Developers',
    subtitle: 'Construction Company',
    category: 'WEBSITE',
    link: 'https://luhaifdevelopers.com/',
  },
  {
    image: '/assets/images/portfolio/app-img12.jpg',
    title: 'Mac Insurance',
    subtitle: 'Insurance Company',
    category: 'WEBSITE',
    link: 'https://macinsurance.in/',
  },

  {
    image: '/assets/images/portfolio/ez-shoprz.jpg',
    title: 'Ezshoprs',
    subtitle: 'Multivendor Ecommerce',
    category: 'WEBSITE',
    link: 'https://ezshoprs.com/',
  },
  {
    image: '/assets/images/portfolio/get-your.jpg',
    title: 'Get Your Assignment Help',
    subtitle: 'Assignment Website',
    category: 'WEBSITE',
    link: 'https://www.getyourassignmenthelp.com/',
  },
  {
    image: '/assets/images/portfolio/hastprada.jpg',
    title: 'Hastprada',
    subtitle: 'NGO',
    category: 'WEBSITE',
    link: 'https://www.hastaprada.org/',
  },
  {
    image: '/assets/images/portfolio/iepf.jpg',
    title: 'IEPF Claim',
    subtitle: 'Claim Advisor',
    category: 'WEBSITE',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/nab.jpg',
    title: 'NAB (National Association for the Blind)',
    subtitle: 'NGO',
    category: 'WEBSITE',
    link: 'https://ngo.nabdelhi.in/',
  },
  {
    image: '/assets/images/portfolio/nizam.jpg',
    title: 'Nizam Uloom',
    subtitle: 'Education Foundation',
    category: 'WEBSITE',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/savers-delight.jpg',
    title: 'Savers Delights',
    subtitle: 'Ecommerce Grocery',
    category: 'WEBSITE',
    link: 'https://www.saversdelights.com/',
  },
  {
    image: '/assets/images/portfolio/rejuva.jpg',
    title: 'Rejuva',
    subtitle: 'Skin Care Products',
    category: 'WEBSITE',
    link: 'https://rejuvaplus.com/',
  },
  {
    image: '/assets/images/portfolio/anysa.jpg',
    title: 'Anysa',
    subtitle: 'Premium Cloth Store',
    category: 'WEBSITE',
    link: 'https://www.anysa.in/',
  },
  {
    image: '/assets/images/portfolio/secret.jpg',
    title: 'Secret Leaves',
    subtitle: 'Green Tea Seller',
    category: 'WEBSITE',
    link: 'https://secretleaves.in/',
  },
  {
    image: '/assets/images/portfolio/roadside.jpg',
    title: 'Roadside',
    subtitle: 'NGO',
    category: 'WEBSITE',
    link: 'https://roadsidefamilyfoundation.org/',
  },
  {
    image: '/assets/images/portfolio/v-store.jpg',
    title: 'Vikram Store',
    subtitle: 'Ecommerce Mobile Shop',
    category: 'WEBSITE',
    link: '#',
  },
  {
    image: '/assets/images/portfolio/kilkari.jpg',
    title: 'Kilkari Care Foundation',
    subtitle: 'NGO',
    category: 'WEBSITE',
    link: 'https://www.kilkaricarefoundation.org/',
  },
  {
    image: '/assets/images/portfolio/fitlook.jpg',
    title: 'Fitlook Originals',
    subtitle: 'Cloth Store',
    category: 'WEBSITE',
    link: 'https://www.fitlookoriginals.com/',
  },
  {
    image: '/assets/images/portfolio/makup.jpg',
    title: 'Makeover by Pooja Walia',
    subtitle: 'Make-up Artist',
    category: 'WEBSITE',
    link: 'https://makeoverbypoojawalia.com/',
  },

  // end website design & development
]
